# -*- coding: utf-8 -*-
"""Projet_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16D5h59HXukneyhUks5WdTqWBlVYCZ2I3

# JuristAI Maroc

## 1- Les Installations
"""

# Commented out IPython magic to ensure Python compatibility.
# Installation des librairies principales
# %pip install -q langchain langchain-community langchain-huggingface
# %pip install -q chromadb
# %pip install -q sentence-transformers
# %pip install -q pypdf
# %pip install -q gradio  # Pour l'interface finale

# Installation des librairies pour l'optimisation GPU (Critique pour Colab gratuit)
# %pip install -q -U torch transformers
# %pip install -q accelerate
# %pip install -q bitsandbytes

"""### Pour sauvgarder a google drive"""

from google.colab import drive
import os

# Monter le Drive
drive.mount('/content/drive')

# Créer un dossier spécifique pour ton projet s'il n'existe pas déjà
project_folder = "/content/drive/MyDrive/Projet_DL"
os.makedirs(project_folder, exist_ok=True)

print(f"✅ Drive monté et dossier prêt : {project_folder}")

"""## Vérification du détection du GPU"""

import torch

# Vérifier si CUDA (le GPU) est disponible
if torch.cuda.is_available():
    print(f"✅ GPU détecté : {torch.cuda.get_device_name(0)}")
    print("Tu es prêt pour la suite %")
else:
    print("❌ Attention : GPU non détecté. Vérifie que tu as bien choisi 'T4 GPU' dans les paramètres d'exécution.")

"""## 2- chargement de data pdf"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q langchain-text-splitters

from langchain_community.document_loaders import PyPDFDirectoryLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# "." signifie le dossier local de Colab
pdf_folder_path = "/content/drive/MyDrive"

print("🧐 Lecture des fichiers PDF déposés...")

loader = PyPDFDirectoryLoader(pdf_folder_path)

try:
    documents = loader.load()

    if len(documents) > 0:
        # --- AJOUT : Extraction des noms de fichiers ---
        # On récupère le chemin source de chaque page et on extrait uniquement le nom du fichier
        import os
        noms_fichiers = set([os.path.basename(doc.metadata['source']) for doc in documents])

        print(f"✅ Réussi % {len(documents)} pages chargées au total.")
        print(f"📄 Fichiers détectés : {', '.join(noms_fichiers)}")
        # -----------------------------------------------

        # Découpage pour le RAG
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=500,
            chunk_overlap=150
        )
        splits = text_splitter.split_documents(documents)
        print(f"✂️ {len(splits)} segments créés. Prêt pour l'étape suivante %")

    else:
        print("❌ Aucun PDF détecté. Assurez-vous d'avoir glissé vos fichiers dans le panneau de gauche (icône dossier).")
except Exception as e:
    print(f"❌ Erreur : {e}")

"""## 3- Création de la Base de Données Vectorielle"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q langchain-huggingface langchain_community

# Commented out IPython magic to ensure Python compatibility.
import os

# 1. Installations de sécurité et Imports
try:
    from langchain_huggingface import HuggingFaceEmbeddings
except ImportError:
#     %pip install -q langchain-huggingface
    from langchain_huggingface import HuggingFaceEmbeddings

from langchain_community.vectorstores import Chroma

from google.colab import drive
drive.mount('/content/drive')

# 2. Configuration du chemin sur Google Drive
# On crée un dossier dédié pour ne pas mélanger les fichiers
drive_save_path = "/content/drive/MyDrive/Projet_DL/chroma_db_juridique"
os.makedirs(drive_save_path, exist_ok=True)

# 3. Choix du modèle d'Embedding (Le traducteur texte -> vecteurs)
# 'paraphrase-multilingual-MiniLM-L12-v2' est excellent pour le français et l'arabe juridique
model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

print(f"🧠 Chargement du modèle d'intelligence sémantique sur le GPU T4...")
embeddings = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs={'device': 'cuda'} # Force l'utilisation du GPU T4
)

# 4. Création et Sauvegarde de la base
print(f"⏳ Transformation des lois en vecteurs... (Patientez, sauvegarde sur le Drive)")

# 'splits' doit avoir été créé à l'étape précédente (le découpage des PDF)
vectorstore = Chroma.from_documents(
    documents=splits,
    embedding=embeddings,
    persist_directory=drive_save_path
)

print(f"✅ Terminé % Votre base de données juridique est sécurisée sur le Drive.")
print(f"📍 Emplacement : {drive_save_path}")

"""## 4- Chargement du Modèle de Langage (LLM)

### LLM TinyLlama-1.1B
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q ctransformers[cuda]
# %pip install -q langchain-community

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain-community langchain ctransformers[cuda]

from langchain_community.llms import CTransformers

config = {
    'max_new_tokens': 256,
    'repetition_penalty': 1.1,
    'temperature': 0.1,
    'context_length': 2048,      # TinyLlama supporte 2048 context
    'gpu_layers': 50
}

print("📥 Chargement de TinyLlama-1.1B (Compatible CTransformers)...")

llm = CTransformers(
    # Ce modèle utilise l'architecture "Llama" classique, donc pas de crash
    model="TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
    model_file="tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
    model_type="llama",          # CTransformers gère très bien ce type
    config=config
)

print("✅ TinyLlama chargé avec succès !")

"""## 5- Création de l'Interface de Chat

"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install gradio
# %pip install chromadb

"""## TinyLlama-1.1B Interface"""

from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings

# 1. Charger la fonction d'embedding (Indispensable pour lire la base)
# Assurez-vous que c'est le même modèle que celui utilisé pour créer la base
print("📥 Chargement des embeddings...")
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# 2. Connexion à votre base Chroma existante
persist_directory = "/content/drive/MyDrive/Projet_DL/chroma_db_juridique"

vectordb = Chroma(
    persist_directory=persist_directory,
    embedding_function=embeddings
)

print(f"✅ Base de données chargée depuis : {persist_directory}")
print(f"   Nombre de documents trouvés : {vectordb._collection.count()}")

import gradio as gr
import re

def generate_response_with_rag(message, history):
    # --- 0. Détection d'intention : Salutations (Intent: Greetings) ---
    # Liste de mots-clés pour les salutations (Français & Arabe)
    greetings_keywords = [
        "bonjour", "salut", "bonsoir", "coucou", "hi", "hello",
        "salam", "marhaba", "ahlan", "salan", "bon jour"
    ]

    # Nettoyage simple du message pour la vérification
    message_clean = message.lower().strip()

    # Si le message est une simple salutation (exacte ou contenue au début)
    # On répond directement sans interroger la base de données (économie de ressources)
    if any(keyword in message_clean for keyword in greetings_keywords) and len(message_clean) < 20:
        return "Bonjour ! Je suis votre assistant juridique. Posez-moi une question sur vos documents. / مرحbا! أنا مساعدك القانوني. تفضل بطرح سؤالك."

    # --- 1. Recherche dans la base de données (Retrieval) ---
    # On cherche les 3 morceaux de texte les plus pertinents
    try:
        docs = vectordb.similarity_search(message, k=3)
        # On compile le contenu trouvé
        context_text = "\n\n".join([doc.page_content for doc in docs])
    except Exception as e:
        return f"Erreur lors de la recherche : {str(e)}"

    # --- 2. Construction du Prompt (Prompt Engineering) ---
    system_prompt = (
        "Tu es un assistant juridique concis. "
        "Réponds dans la même langue que la question (Français ou Arabe). "
        "Sois extrêmement bref et direct (maximum 2 phrases). "
        "Utilise UNIQUEMENT le contexte fourni. "
        "Si la réponse n'est pas dans le contexte, dis 'Je ne sais pas' ou 'لا أعلم'."
    )

    formatted_prompt = f"""{system_prompt}

CONTEXTE :
{context_text}

QUESTION : {message}

RÉPONSE :"""

    # --- 3. Génération de la réponse ---
    response = llm.invoke(formatted_prompt)

    if hasattr(response, 'content'):
        return response.content
    elif isinstance(response, str):
        return response
    else:
        return str(response)

# Création de l'interface
demo = gr.ChatInterface(
    fn=generate_response_with_rag,
    title="⚖️ Assistant Juridique (Connecté Drive)",
    description="Posez une question, je chercherai la réponse dans vos documents.",
    examples=["Bonjour", "Quelles sont les conditions du contrat ?", "Délai de préavis ?"]
)

demo.launch(share=True, debug=True)

"""## Mistral 7B Interface"""

!pip install -q -U torch transformers accelerate bitsandbytes langchain langchain-community langchain-huggingface chromadb sentence-transformers gradio

import torch
import gradio as gr
from google.colab import drive
from langchain_huggingface import HuggingFaceEmbeddings, HuggingFacePipeline
from langchain_community.vectorstores import Chroma
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig

# -----------------------------------------------------------------------------
# 1. MONTAGE DU DRIVE
# -----------------------------------------------------------------------------
# Si le drive n'est pas déjà monté
if not torch.cuda.is_available():
    print("⚠️ ATTENTION : Vous n'utilisez pas le GPU. Activez-le dans 'Modifier le type d'exécution'.")

try:
    drive.mount('/content/drive')
except:
    print("Drive déjà monté ou erreur de montage.")

# -----------------------------------------------------------------------------
# 2. CHARGEMENT DE VOTRE BASE DE DONNÉES (CHROMA)
# -----------------------------------------------------------------------------
print("\n📥 Chargement de la base de données...")
PERSIST_DIRECTORY = "/content/drive/MyDrive/Projet_DL/chroma_db_juridique"

# IMPORTANT : On utilise le même modèle d'embedding que lors de la création
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

vectordb = Chroma(
    persist_directory=PERSIST_DIRECTORY,
    embedding_function=embedding_model
)
print(f"✅ Base chargée. {vectordb._collection.count()} documents disponibles.")

# -----------------------------------------------------------------------------
# 3. CHARGEMENT DE MISTRAL 7B (Optimisé 4-bit)
# -----------------------------------------------------------------------------
print("\n🚀 Chargement de Mistral 7B (Cela prend 2-3 minutes)...")

model_id = "mistralai/Mistral-7B-Instruct-v0.2"

# Configuration pour faire tenir le modèle sur le GPU gratuit (T4)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

# Pipeline de génération
text_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,       # Longueur max de la réponse
    temperature=0.1,          # Faible créativité pour rester factuel (juridique)
    repetition_penalty=1.1,
    return_full_text=False
)

llm = HuggingFacePipeline(pipeline=text_pipeline)
print("✅ Mistral est prêt !")

# -----------------------------------------------------------------------------
# 4. LOGIQUE DU CHATBOT (RAG + Prompt Mistral)
# -----------------------------------------------------------------------------
def chat_logic(message, history):
    # A. Filtre Salutations (pour répondre vite sans chercher dans la base)
    salutations = ["bonjour", "salut", "bonsoir", "salam", "hi", "hello"]
    if message.lower().strip() in salutations:
        return "Bonjour ! Je suis votre assistant juridique IA. Posez-moi une question sur vos documents."

    # B. Recherche dans la base (Retrieval)
    try:
        docs = vectordb.similarity_search(message, k=3) # On prend les 3 meilleurs extraits
        if not docs:
            return "Désolé, je n'ai trouvé aucune information pertinente dans vos documents pour répondre à cette question."

        # Concaténation du contexte
        context_text = "\n\n".join([doc.page_content for doc in docs])

        # Extraction des sources (pour affichage)
        sources_list = sorted(list(set([doc.metadata.get('source', 'Inconnu').split('/')[-1] for doc in docs])))
        sources_display = "\n".join([f"- {s}" for s in sources_list])

    except Exception as e:
        return f"Erreur de recherche : {e}"

    # C. Construction du Prompt (Format Mistral Instruct)
    # Les balises [INST] sont cruciales pour que Mistral comprenne que c'est une instruction
    prompt_template = f"""<s>[INST] Tu es un assistant juridique expert. Utilise le contexte ci-dessous pour répondre à la question de l'utilisateur.
Si la réponse ne se trouve pas dans le contexte, dis simplement "Je ne sais pas".
Réponds dans la même langue que la question.

CONTEXTE :
{context_text}

QUESTION :
{message} [/INST]"""

    # D. Génération de la réponse
    try:
        response = llm.invoke(prompt_template)
        response_text = response if isinstance(response, str) else response.content

        # Ajout des sources à la fin
        final_output = f"{response_text}\n\n----------------\n📚 Sources :\n{sources_display}"
        return final_output

    except Exception as e:
        return f"Erreur de génération : {e}"

# -----------------------------------------------------------------------------
# 5. LANCEMENT DE L'INTERFACE GRADIO
# -----------------------------------------------------------------------------
demo = gr.ChatInterface(
    fn=chat_logic,
    title="🤖 Assistant Juridique (Mistral 7B + RAG)",
    description="Posez vos questions juridiques. Je cherche la réponse dans votre base ChromaDB.",
    examples=["Quelles sont les conditions de validité ?", "Quel est le délai de préavis ?", "Que dit l'article 4 ?"],
    theme="soft"
)

print("\n🌐 Lancement de l'interface...")
demo.launch(share=True, debug=True)

"""##Comparaison (TinyLlama-1.1B - Mistral 7B )
### Temps (s)	Vitesse (tok/s)	VRAM Max (GB)  
"""

# 1. INSTALLATION DES DÉPENDANCES
# On installe les bibliothèques nécessaires pour gérer les modèles et la quantification
!pip install -q -U torch transformers accelerate bitsandbytes sentencepiece

import torch
import time
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig
import gc

# ---------------------------------------------------------
# 2. CONFIGURATION
# ---------------------------------------------------------

# Configuration pour charger Mistral en 4-bits (économie de VRAM)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Fonction pour charger un modèle, le tester, puis le décharger pour libérer la mémoire
def evaluer_modele(model_id, nom_modele, context, question, use_4bit=False):
    print(f"\n--- Chargement de {nom_modele} ---")

    # Gestion de la config 4-bit si nécessaire
    quant_config = bnb_config if use_4bit else None

    # Chargement du Tokenizer et du Modèle
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=quant_config,
        device_map="auto",
        torch_dtype=torch.float16 if not use_4bit else None
    )

    # Préparation du prompt format RAG
    # Note: On force un formatage clair pour aider TinyLlama
    prompt_rag = f"""Vous êtes un assistant juridique expert. Utilisez le contexte suivant pour répondre à la question.

    CONTEXTE JURIDIQUE:
    {context}

    QUESTION:
    {question}

    RÉPONSE:"""

    inputs = tokenizer(prompt_rag, return_tensors="pt").to("cuda")

    # Mesure de performance
    torch.cuda.reset_peak_memory_stats()
    start_time = time.time()

    # Génération
    outputs = model.generate(
        **inputs,
        max_new_tokens=250, # Limite la longueur pour comparer équitablement
        do_sample=True,
        temperature=0.1 # Température basse pour être factuel
    )

    end_time = time.time()

    # Calcul des métriques
    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    reponse_seule = generated_text.replace(prompt_rag, "").strip()

    total_time = end_time - start_time
    num_tokens = len(outputs[0]) - len(inputs['input_ids'][0]) # Tokens générés seulement
    tokens_per_sec = num_tokens / total_time
    max_vram = torch.cuda.max_memory_allocated() / 1024**3 # En GB

    print(f"✅ Terminé en {total_time:.2f}s")

    # Nettoyage Mémoire (CRUCIAL sur Colab)
    del model
    del tokenizer
    torch.cuda.empty_cache()
    gc.collect()

    return {
        "Modèle": nom_modele,
        "Temps (s)": round(total_time, 2),
        "Vitesse (tok/s)": round(tokens_per_sec, 2),
        "VRAM Max (GB)": round(max_vram, 2),
        "Réponse": reponse_seule
    }

# ---------------------------------------------------------
# 3. DONNÉES DE TEST (Simulez votre contexte juridique ici)
# ---------------------------------------------------------

contexte_juridique = """
Selon l'article 45 du code du travail marocain, l'employeur est tenu de délivrer au salarié un certificat de travail à la fin du contrat, quel que soit le motif de la rupture.
Ce certificat doit indiquer exclusivement la date d'entrée du salarié, la date de sa sortie et les postes occupés.
Toute mention défavorable au salarié est interdite.
"""

question_test = "Que doit contenir le certificat de travail selon la loi et quelles mentions sont interdites ?"

# ---------------------------------------------------------
# 4. EXÉCUTION DU TEST COMPARATIF
# ---------------------------------------------------------

resultats = []

# Test 1: TinyLlama 1.1B (Pas besoin de 4bit, il est petit)
res_tiny = evaluer_modele(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    "TinyLlama-1.1B",
    contexte_juridique,
    question_test,
    use_4bit=False
)
resultats.append(res_tiny)

# Test 2: Mistral 7B (Version Instruct v0.2) - Avec 4bit pour tenir sur Colab
res_mistral = evaluer_modele(
    "mistralai/Mistral-7B-Instruct-v0.2",
    "Mistral-7B",
    contexte_juridique,
    question_test,
    use_4bit=False
)
resultats.append(res_mistral)

# ---------------------------------------------------------
# 5. AFFICHAGE DU TABLEAU
# ---------------------------------------------------------
df = pd.DataFrame(resultats)
print("\n\n=== RÉSULTATS DE LA COMPARAISON ===")
display(df[["Modèle", "Temps (s)", "Vitesse (tok/s)", "VRAM Max (GB)"]])

print("\n--- Réponse TinyLlama ---")
print(df.iloc[0]['Réponse'])

print("\n--- Réponse Mistral ---")
print(df.iloc[1]['Réponse'])

"""### comparaison F1 score et Accuracy"""

print("⏳ Installation des dépendances...")
!pip install -q -U torch transformers accelerate bitsandbytes sentencepiece matplotlib pandas
!pip install -q -U langchain langchain-community langchain-huggingface chromadb sentence-transformers

# ==========================================
# 1. INSTALLATION & SETUP
# ==========================================
print("⏳ Installation des dépendances...")
!pip install -q -U torch transformers accelerate bitsandbytes sentencepiece matplotlib "pandas==2.2.2"
!pip install -q -U langchain langchain-community langchain-huggingface chromadb sentence-transformers
!pip install -q -U rouge-score scikit-learn

import torch
import time
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import gc
import re
import string
from collections import Counter

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from google.colab import drive

# Pour les métriques avancées
from sklearn.metrics.pairwise import cosine_similarity
from rouge_score import rouge_scorer

# Monter le Drive
print("📂 Connexion au Google Drive...")
drive.mount('/content/drive')

# ==========================================
# 2. CHARGEMENT DE LA BASE VECTORIELLE
# ==========================================

# Modèle d'embedding (doit être le même que celui utilisé pour créer la DB)
NOM_MODELE_EMBEDDING = "sentence-transformers/all-MiniLM-L6-v2"
embeddings = HuggingFaceEmbeddings(model_name=NOM_MODELE_EMBEDDING)

# ⚠️ MODIFIEZ CE CHEMIN VERS VOTRE DOSSIER CHROMA
chemin_db = "/content/drive/MyDrive/Projet_DL/chroma_db_juridique"

print(f"🗄️ Chargement de la ChromaDB depuis : {chemin_db}")
try:
    db = Chroma(persist_directory=chemin_db, embedding_function=embeddings)
    nb_docs = db._collection.count()
    print(f"✅ Base chargée. Documents indexés : {nb_docs}")
    if nb_docs == 0:
        print("⚠️ ATTENTION : La base est vide !")
except Exception as e:
    print(f"❌ Erreur DB (Vérifiez le chemin) : {e}")
    # Création d'une DB vide temporaire pour éviter que le code plante
    db = Chroma.from_texts(["Document test vide"], embeddings)
    print("⚠️ Base temporaire créée. Résultats non fiables.")

def recuperer_contexte(question, k=3):
    """Récupère les documents les plus proches de la question."""
    try:
        docs = db.similarity_search(question, k=k)
        if not docs:
            print(f"⚠️ Aucun document trouvé pour: {question[:50]}...")
            return "Contexte juridique non disponible."
        contexte = "\n\n".join([doc.page_content for doc in docs])
        return contexte
    except Exception as e:
        print(f"❌ Erreur récupération contexte: {e}")
        return "Erreur de récupération du contexte."

# ==========================================
# 3. FONCTIONS DE MÉTRIQUES AVANCÉES (4 TYPES)
# ==========================================

# Initialisation du calculateur Rouge
rouge_calc = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)

def normalize_text(s):
    """Nettoyage : minuscules, suppression articles/ponctuation."""
    if not s:
        return ""
    def remove_articles(text):
        return re.sub(r'\b(le|la|les|un|une|de|des|l|d)\b', ' ', text)
    def white_space_fix(text):
        return ' '.join(text.split())
    def remove_punc(text):
        return ''.join(ch for ch in text if ch not in set(string.punctuation))
    return white_space_fix(remove_articles(remove_punc(s.lower())))

def compute_advanced_metrics(prediction, truth, embedding_model):
    """
    Calcule 4 métriques :
    1. Exact Match (0/1)
    2. F1 Token (Recouvrement lexical)
    3. Rouge-L (Structure de phrase)
    4. Sémantique (Cosine similarity des embeddings)
    """
    pred_norm = normalize_text(prediction)
    truth_norm = normalize_text(truth)

    # 1. Exact Match
    exact_match = 1.0 if pred_norm == truth_norm else 0.0

    # 2. F1 Score (Lexical)
    pred_tokens = pred_norm.split()
    truth_tokens = truth_norm.split()

    if not pred_tokens or not truth_tokens:
        f1 = 1.0 if pred_tokens == truth_tokens else 0.0
    else:
        common = Counter(pred_tokens) & Counter(truth_tokens)
        num_same = sum(common.values())
        if num_same == 0:
            f1 = 0.0
        else:
            precision = 1.0 * num_same / len(pred_tokens)
            recall = 1.0 * num_same / len(truth_tokens)
            f1 = (2 * precision * recall) / (precision + recall)

    # 3. ROUGE-L (Structurelle)
    try:
        scores_rouge = rouge_calc.score(truth_norm, pred_norm)
        rouge_l = scores_rouge['rougeL'].fmeasure
    except Exception as e:
        print(f"⚠️ Erreur ROUGE: {e}")
        rouge_l = 0.0

    # 4. Sémantique (Cosine Similarity)
    try:
        # Vectorisation des deux phrases
        vec_pred = embedding_model.embed_query(prediction)
        vec_truth = embedding_model.embed_query(truth)
        # Calcul cosine (reshape nécessaire pour sklearn)
        similarity = cosine_similarity([vec_pred], [vec_truth])[0][0]
        similarity = max(0.0, similarity)  # Éviter les valeurs négatives
    except Exception as e:
        print(f"⚠️ Erreur embedding metrics : {e}")
        similarity = 0.0

    return {
        "Exact_Match": round(exact_match, 2),
        "F1_Token": round(f1, 4),
        "Rouge_L": round(rouge_l, 4),
        "Semantique": round(similarity, 4)
    }

def evaluer_pertinence_contexte(question, contexte):
    """Mesure la pertinence du contexte récupéré."""
    mots_q = set(normalize_text(question).split())
    mots_c = set(normalize_text(contexte).split())
    if not mots_q:
        return 0.0
    overlap = len(mots_q & mots_c) / len(mots_q)
    return round(overlap, 3)

# ==========================================
# 4. MOTEUR D'ÉVALUATION
# ==========================================

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

def evaluer_modele_rag(model, tokenizer, nom_modele, question, ground_truth, embedding_model):
    """Évalue un modèle sur une question avec RAG."""

    # RAG : Récupération du contexte
    contexte = recuperer_contexte(question, k=3)
    pertinence = evaluer_pertinence_contexte(question, contexte)

    # Construction du prompt
    prompt = f"""Contexte juridique:
{contexte}

Question: {question}

Réponse courte et précise:"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=2048).to("cuda")

    # Génération
    start_time = time.time()
    try:
        outputs = model.generate(
            **inputs,
            max_new_tokens=100,
            do_sample=False,
            temperature=0.7,
            pad_token_id=tokenizer.eos_token_id
        )
        duration = time.time() - start_time

        full_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Extraction de la réponse (on retire le prompt)
        reponse = full_text[len(prompt):].strip()
        if '\n\n' in reponse:
            reponse = reponse.split('\n\n')[0].strip()
        elif '\n' in reponse:
            reponse = reponse.split('\n')[0].strip()

        # Limite de longueur
        reponse = reponse[:300] if len(reponse) > 300 else reponse

    except Exception as e:
        print(f"❌ Erreur génération pour {nom_modele}: {e}")
        reponse = "[Erreur de génération]"
        duration = 0.0
        pertinence = 0.0

    # Calcul des métriques
    metrics = compute_advanced_metrics(reponse, ground_truth, embedding_model)

    print(f"   📝 {nom_modele} -> F1: {metrics['F1_Token']:.3f} | Sem: {metrics['Semantique']:.3f} | Pert: {pertinence:.3f}")

    return {
        "Modèle": nom_modele,
        "Question": question,
        "Vérité Terrain": ground_truth,
        "Réponse Générée": reponse,
        "Exact Match": metrics['Exact_Match'],
        "F1 Token": metrics['F1_Token'],
        "Rouge-L": metrics['Rouge_L'],
        "Sémantique": metrics['Semantique'],
        "Pertinence Ctx": pertinence,
        "Temps (s)": round(duration, 2)
    }

# ==========================================
# 5. DATASET DE TEST
# ==========================================

# Dataset de test étendu (ajoutez plus d'exemples pour des résultats fiables)
dataset_test = [

    {

        "question": "Quelle est la durée légale de travail au Maroc ?",

        "verite": "44 heures par semaine"

    },

    {

        "question": "Que doit contenir le certificat de travail ?",

        "verite": "La date d'entrée, la date de sortie et les postes occupés"

    },

    {

        "question": "Quelle est la durée du préavis de démission ?",

        "verite": "8 jours pour moins d'un an d'ancienneté"

    },

    {

        "question": "Quel est l'âge minimum pour travailler au Maroc ?",

        "verite": "15 ans"

    },

    {

        "question": "Combien de jours de congé annuel payé ?",

        "verite": "1.5 jours par mois de travail effectif"

    }

]

print(f"\n📊 Dataset de test : {len(dataset_test)} questions")

# ==========================================
# 6. LANCEMENT DE L'ÉVALUATION
# ==========================================

resultats_globaux = []

# Liste des modèles à tester (ajoutez use_4bit=True pour économiser la RAM)
modeles = [
    ("TinyLlama/TinyLlama-1.1B-Chat-v1.0", "TinyLlama", False),
    ("mistralai/Mistral-7B-Instruct-v0.2", "Mistral-7B", False),  # ✅ 4-bit activé
]

print("\n" + "="*60)
print("🚀 DÉBUT DE L'ÉVALUATION")
print("="*60)

# Boucle principale
for model_id, nom, use_4bit in modeles:
    print(f"\n{'='*60}")
    print(f"📦 Chargement de {nom}...")
    print(f"   Quantification 4-bit: {'✅ OUI' if use_4bit else '❌ NON'}")
    print(f"{'='*60}")

    try:
        tok = AutoTokenizer.from_pretrained(model_id)

        # Ajout du pad_token si nécessaire
        if tok.pad_token is None:
            tok.pad_token = tok.eos_token

        mod = AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=bnb_config if use_4bit else None,
            device_map="auto",
            torch_dtype=torch.float16 if not use_4bit else None,
            low_cpu_mem_usage=True
        )

        print(f"✅ {nom} chargé avec succès")
        print(f"   Mémoire GPU utilisée: {torch.cuda.memory_allocated()/1e9:.2f} GB")

        # Évaluation sur chaque question
        for i, item in enumerate(dataset_test, 1):
            print(f"\n❓ Question {i}/{len(dataset_test)}: {item['question'][:60]}...")
            res = evaluer_modele_rag(
                mod, tok, nom,
                item["question"],
                item["verite"],
                embeddings
            )
            resultats_globaux.append(res)

        # Nettoyage mémoire GPU entre chaque modèle
        print(f"\n🧹 Nettoyage mémoire pour {nom}...")
        del mod, tok
        torch.cuda.empty_cache()
        gc.collect()
        print(f"   Mémoire GPU libérée: {torch.cuda.memory_allocated()/1e9:.2f} GB")

    except Exception as e:
        print(f"\n❌ ERREUR CRITIQUE sur {nom}:")
        print(f"   {type(e).__name__}: {e}")
        print("   Le modèle sera ignoré.")
        continue

# ==========================================
# 7. AFFICHAGE DES RÉSULTATS
# ==========================================

print("\n" + "="*60)
print("📊 RÉSULTATS FINAUX")
print("="*60)

if resultats_globaux:
    df = pd.DataFrame(resultats_globaux)

    # Tableau détaillé
    print("\n=== TABLEAU DÉTAILLÉ ===")
    display(df[["Modèle", "Question", "Réponse Générée", "F1 Token", "Rouge-L", "Sémantique", "Pertinence Ctx"]])

    # Statistiques moyennes par modèle
    print("\n=== MOYENNES PAR MODÈLE ===")
    metriques_cols = ["Exact Match", "F1 Token", "Rouge-L", "Sémantique", "Pertinence Ctx", "Temps (s)"]
    df_mean = df.groupby("Modèle")[metriques_cols].mean()
    display(df_mean)

    # Sauvegarde des résultats
    chemin_csv = "/content/drive/MyDrive/Projet_DL/resultats_rag_evaluation.csv"
    try:
        df.to_csv(chemin_csv, index=False, encoding='utf-8')
        print(f"\n💾 Résultats sauvegardés: {chemin_csv}")
    except Exception as e:
        print(f"⚠️ Erreur sauvegarde CSV: {e}")

    # ==========================================
    # 8. VISUALISATIONS
    # ==========================================

    print("\n📈 Génération des graphiques...")

    # Graphique 1 : Comparaison Multi-Métrique
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # Barres groupées
    metriques_viz = ["F1 Token", "Rouge-L", "Sémantique", "Pertinence Ctx"]
    df_viz = df.groupby("Modèle")[metriques_viz].mean()

    ax1 = axes[0]
    df_viz.plot(kind='bar', ax=ax1, rot=0, width=0.8, colormap='viridis')
    ax1.set_title("Performance RAG : Comparaison Multi-Métrique", fontsize=14, fontweight='bold')
    ax1.set_ylabel("Score (0-1)", fontsize=12)
    ax1.set_ylim(0, 1.15)
    ax1.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left', title="Métriques")
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    # Ajout des valeurs sur les barres
    for container in ax1.containers:
        ax1.bar_label(container, fmt='%.3f', padding=3, fontsize=9)

    # Graphique 2 : Temps d'inférence
    ax2 = axes[1]
    temps_moy = df.groupby("Modèle")["Temps (s)"].mean()
    bars = ax2.bar(temps_moy.index, temps_moy.values, color=['#3498db', '#e74c3c'], width=0.6)
    ax2.set_title("Temps Moyen d'Inférence", fontsize=14, fontweight='bold')
    ax2.set_ylabel("Temps (secondes)", fontsize=12)
    ax2.grid(axis='y', linestyle='--', alpha=0.5)

    # Valeurs sur les barres
    for bar in bars:
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.2f}s', ha='center', va='bottom', fontsize=11, fontweight='bold')

    plt.tight_layout()
    plt.savefig('/content/drive/MyDrive/Projet_DL/graphique_rag_evaluation.png', dpi=300, bbox_inches='tight')
    print("💾 Graphique sauvegardé: graphique_rag_evaluation.png")
    plt.show()

    # Graphique 3 : Heatmap des performances
    plt.figure(figsize=(10, 6))
    pivot_data = df.pivot_table(
        values='F1 Token',
        index='Question',
        columns='Modèle',
        aggfunc='mean'
    )

    import seaborn as sns
    sns.heatmap(pivot_data, annot=True, fmt='.3f', cmap='RdYlGn', center=0.5,
                cbar_kws={'label': 'Score F1'}, linewidths=0.5)
    plt.title("Heatmap : Performance par Question", fontsize=14, fontweight='bold')
    plt.xlabel("Modèle", fontsize=12)
    plt.ylabel("Question", fontsize=12)
    plt.xticks(rotation=0)
    plt.yticks(rotation=0, fontsize=8)
    plt.tight_layout()
    plt.savefig('/content/drive/MyDrive/Projet_DL/heatmap_rag_evaluation.png', dpi=300, bbox_inches='tight')
    print("💾 Heatmap sauvegardée: heatmap_rag_evaluation.png")
    plt.show()

    print("\n✅ ÉVALUATION TERMINÉE AVEC SUCCÈS !")

else:
    print("❌ Aucun résultat généré. Vérifiez les erreurs ci-dessus.")

print("\n" + "="*60)
print("🏁 FIN DU SCRIPT")
print("="*60)